import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const pagesMap = [
  {
    href: "/posts",
    id: "location:posts",
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          {pagesMap.map((p) => (
            <Link href={p.href} key={p.id}>
              <a>posts</a>
            </Link>
          ))}
        </nav>
      </header>
    </div>
  );
}
